name: Compilación y ejecución de pruebas

# Eventos que gatillan la ejecución del pipeline
on:
  # Ejecución manual
  workflow_dispatch:
  # Cada vez que se haga un push al repositorio
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # Descargar última version desde el repositorio
      - name: Descargar del repositorio
        uses: actions/checkout@v4

      # Instalar Java LTS compatible con Maven/JavaFX
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Preparar entorno gráfico headless para JavaFX
      - name: Instalar dependencias de entorno gráfico
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # Compilar y empaquetar
      - name: Compilar y empaquetar
        run: mvn --batch-mode -DskipTests package

      # Ejecutar pruebas automatizadas (JUnit)
      - name: Ejecutar pruebas
        run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' mvn --batch-mode test

      # Generar un reporte de pruebas
      - name: Reporte de pruebas
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'

      # (Opcional) Desplegar
